name: Despliege de una página web estática
on: 
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group:"pages"
  cancel-in-progress:false
jobs:
  despliege:
    environment:
      name: github-pages
      url: ${{steps, deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: '.'
      - name: Despliege
        id: deployment
        uses: actions/deploy-pages@v4.0.5
        
